groups:
  - name: games
    items:
      - FL 2025
      # - Watch Dogs 2
      - Blood Strike
      # - Balatro
      # - Wrestling Empire
      # - Roblox
      # - Zenless Zen Zero
      # - The Sims 4
      - WWE 2K14
      # - Inside
      - Fall Guys
      - Ghostrunner
default_group: games
