groups:
  - name: games
    items:
      - eFootball
      # - Blood Strike
      # - Wrestling Empire
      # - Fall Guys
      - "ETS 2"
      - Dying Light
      - A Space for the unbound
      - "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated"
default_group: games
