default_group: games
groups:
  - name: games
    items:
      - "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated"
      - "Crash Bandicoot™ N. Sane Trilogy"
      - "Marvel's Guardians of the Galaxy"
      - "DEATH STRANDING"
      # - Blood Strike
      - eFootball
      - "Hell Let Loose"
      - "F1 2018"
      # - Wrestling Empire
      # - "ETS 2"
