groups:
  - name: games
    items:
      - A Space for the unbound
      - "SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated"
      - "A Plague Tale: Innocence"
      - "Crash Bandicoot™ N. Sane Trilogy"
      - "The Operator"
      # - Blood Strike
      - eFootball
      - "Hell Let Loose"
      # - Wrestling Empire
      # - "ETS 2"
      # - Sifu
default_group: games
