default_group: games
groups:
  - name: games
    items:
      - "Crash Bandicoot™ N. Sane Trilogy"
      - "Marvel's Guardians of the Galaxy"
      - "DEATH STRANDING"
      - "LEGO® Star Wars™: The Skywalker Saga"
      - eFootball
      - "Control"
