groups:
  - name: games
    items:
      - FL 2025
      - Marvel Rivals
      - Watch Dogs 2
      - Blood Strike
      - Balatro
      - Stumble Guys
      - Wrestling Empire
      - Roblox
      - Left 4 Dead 2
      - Asphalt Legends Unite
      - BioShock
default_group: games
