groups:
  - name: games
    items:
      - eFootball
      - Blood Strike
      - Wrestling Empire
      - Fall Guys
      - "ETS 2"
      # - Alba
      # - The Murder of Sonic The Hedgehog
      - Dying Light
      - Brothers - A Tale of Two Sons
default_group: games
