groups:
  - name: games
    items:
      - eFootball
      # - Watch Dogs 2
      - Blood Strike
      # - Balatro
      - Wrestling Empire
      # - Roblox
      # - WWE 2K14
      - Fall Guys
      - Ghostrunner
default_group: games
