groups:
  - name: games
    items:
      - eFootball
      - Blood Strike
      - Wrestling Empire
      - Fall Guys
      - "ETS 2"
      - Dying Light
      # - Brothers - A Tale of Two Sons
      - Resident Evil 2
default_group: games
