groups:
  - name: games
    items:
      - eFootball
      - Blood Strike
      - Wrestling Empire
      - Fall Guys
      # - "Wolfenstein: The New Order"
      - "ETS 2"
      - Alba
default_group: games
