groups:
  - name: games
    items:
      - eFootball
      # - Watch Dogs 2
      - Blood Strike
      # - Balatro
      - Wrestling Empire
      # - Roblox
      - Fall Guys
      # - Ghostrunner
default_group: games
