groups:
  - name: games
    items:
      - FL 2025
      # - Watch Dogs 2
      - Blood Strike
      # - Balatro
      # - Stumble Guys
      - Wrestling Empire
      # - Roblox
      - Rise of the Tomb Raider
      # - TETR.IO
      - Zenless Zen Zero
      - The Sims 4
default_group: games
