groups:
  - name: games
    items:
      - eFootball
      # - Watch Dogs 2
      - Blood Strike
      - Wrestling Empire
      - Fall Guys
      - "Wolfenstein: The New Order"
      - "ETS 2"
default_group: games
